#!/bin/bash

case "$1" in 
start)
   /home/pi/wheelofbeer/scripts/beerwheel.sh &
   echo $!>/var/run/beerwheel.pid
   ;;
stop)
   kill `cat /var/run/beerwheel.pid`
   rm /var/run/beerwheel.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/beerwheel.pid ]; then
      echo The beerwheel is running, pid=`cat /var/run/beerwheel.pid`
   else
      echo beerwheel is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
